Fix missing import
Fix error:
node_modules/@nrwl/workspace/src/schematics/remove/schema.d.ts:1:33 - error TS2503: Cannot find namespace 'json'.
export interface Schema extends json.JsonObject {
                                  ~~~~
Found 1 error.