chore(nx-dev): improve error message when changelog fails due to expired token (#32389)
This PR improves our error message whenever our GitHub API token expires
so we're not confused about what's broken. It expires each year as
required by Octokit.

Current error:

```
 Error occurred prerendering page "/changelog". Read more:  https://nextjs.org/docs/messages/prerender-error
  HttpError: Bad credentials
```

New error:

```
Error occurred prerendering page "/changelog". Read more: https://nextjs.org/docs/messages/prerender-error

Error: The GitHub token is invalid or has expired. Please provide a new Personal Access Token (PAT) via the GITHUB_TOKEN environment variable.
```

(cherry picked from commit f51215cb0d9cf4e40a762906b2c7543a873b643b)